### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by vk4tux** [juribeparada/YSF2DMR#1]
Andy, Can you comment on usage? Is the software designed to run with other mmdvm software as a 'plugin'
Thankyou

Adrian ... vk4tux

**Comment by juribeparada** [comment]
Hi Adrian,

Well, I'm still working on this code, and I will add the support to link YSF2DMR to YSFGateway. For now, you can change the default ports (42000, 42013) to 3200 and 4200, to connect directly to MMDVMHost (as YSFGateway).

I'm planning to make more changes during the following days.

Regards,
Andy CA6JAU
