### ISSUE TITLE
Compile Error in YSF2DMR.cpp (TGSel branch)

### ISSUE THREAD

**Issue by ve1aic** [juribeparada/YSF2DMR#10]
YSF2DMR.cpp: In member function std::string CYSF2DMR::getSrcYSF(const unsigned char*):

YSF2DMR.cpp:1072:16: error: find_if is not a member of std

  trimmed.erase(std::find_if(trimmed.rbegin(), trimmed.rend(), std::not1(std::ptr_fun<int, int>(std::isspace))).base(), trimmed.end());
                ^
Makefile:20: recipe for target 'YSF2DMR.o' failed
make: *** [YSF2DMR.o] Error 1

**Comment by juribeparada** [comment]
In general I compile first in macOS, then Linux and Windows. What Linux are you using?

**Comment by ve1aic** [comment]
Raspbian Jessie

**Comment by juribeparada** [comment]
Try again. TGSel brach is under development, it isn't ready yet.

**Comment by ve1aic** [comment]
Thanks Andy, compiled ok. Now to test the TGSel.
Have been using YSF2DMR for past few days and works well on my dev system (Zum_Libre).

**Comment by ve1aic** [comment]
Using Wires-X to select TG's instead of Rooms works great so far.
Good Job.
