### ISSUE TITLE
Quoted config

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/YSF2DMR#11]
Andy, I recently asked Jonathan to modify his software to accept (and remove on parse) quotes in the config - this has become important as some BM servers are using characters I can't handle without quotes;

It also helps solve some other issues with the way I handle the config files in PHP, would it be possible for you to add similar code for YSF2DMR too please?

Andy
MW0MWZ

**Comment by juribeparada** [comment]
OK Andy, no problem, I will try to implement during the following days.

**Comment by AndyTaylorTweet** [comment]
Just in case you need some inspiration....
https://github.com/g4klx/MMDVMHost/commit/b694f85461e789f98cff5a65fd32176da3e3e1ab

**Comment by juribeparada** [comment]
Please check now
