### ISSUE TITLE
Finishing support for XLX connection

### ISSUE THREAD

**Issue by ea4fvb** [juribeparada/YSF2DMR#12]
Hello Andy a quick class on how to use your update of the "Finishing support for XLX connection" 

great work andy Genio :)
73
EA4FVB - Pablo

**Comment by juribeparada** [comment]
You only need to uncomment:

XLXFile=XLXHosts.txt
XLXReflector=950
XLXModule=D

and replace XLXReflector and XLXModule according your preferences. Also, you need to configure the DMR port:

Port=62030

StartupDstId, StartupPC and Address don't care in XLX mode.

**Comment by ea4fvb** [comment]
thank you for your fast answer Andy, I connerct to address IP not to XLXReflector selected, my YSF2DMR.ini is:

[DMR Network]
Id=2145034
XLXFile=XLXHosts.txt
XLXReflector=241
XLXModule=D
StartupDstId=9
# For TG call: StartupPC=0
StartupPC=0
Address=xlx909.ealink.es
Port=62030

the conection goes to XLX909 instead of 241, and startup module is white it is not D or it is not start module in XLXHosts.txt file (4004, it is D too) 

well actually my problem is not connect, is that I do not know how to select the default module with my FT1XD on a XLX reflector

73
Pablo - EA4FVB

**Comment by iw9grl** [comment]
Hi Pablo, the Port=62030 works only for XLX connection , the XLX number is read inside the XLXHost.txt file ( verify if the path is correct ), the "Address="  parameter is used for DRM server connection and works when you use the Port=62031 ( the StartupDstID works only when Port=62031 ) , in my system works in this way, hoping to describe it correctly ... 73 de IW9GRL

**Comment by ea4fvb** [comment]
Perfectly explained Daniele :)

but it was my fault, sorry guys ... too many linux devices on the table. I have updated 3 boards at the same time to latest version of YSF2DMR and forget the "make" just in which I am testing.

novice error :o

It works perfectly
73 - EA4FVB
