### ISSUE TITLE
No ongoing StreamID for "DMRD" YSF -> DMR

### ISSUE THREAD

**Issue by oe1kbc** [juribeparada/YSF2DMR#13]
I found this because we send "DMRD" packets comming from YSF2DMR to XLXD and no audio was heard.

A quick an dirty coding to get audio now:

					if (fi == YSF_FI_HEADER) {
						if (ysfPayload.processHeaderData(buffer + 35U)) {
							std::string ysfSrc = ysfPayload.getSource();
							std::string ysfDst = ysfPayload.getDest();
							LogMessage("Received YSF Header: Src: %s Dst: %s", ysfSrc.c_str(), ysfDst.c_str());

							m_dmrNetwork->reset(2U);	// KBC

							m_srcid = findYSFID(ysfSrc, true);
							m_conv.putYSFHeader();
							m_ysfFrames = 0U;
						}

Andy please check my patch.

Thank you
73 de Kurt

**Comment by juribeparada** [comment]
Hi, can you describe the issue better?, I don't understand why this is necessary, I know some people running this and they don't have any audio issue with XLX.

**Comment by oe1kbc** [comment]
Ok it seem to be not a problem, so we are happy with my batch … 
Thank you so much
73 de Kurt
OE1KBC

**Comment by juribeparada** [comment]
Maybe I didn't explain me correctly, I mean without your patch, YSF2DMR -> XLX works OK, then I don't understand your issue, can you explain what is the problem that you have?. BTW, this is a legacy YSF2DMR repository, the latest code is in MMDVM_CM.

**Comment by oe1kbc** [comment]
Jorge,

i’ll try again

 

*	yes I use MMDVM_CM source.

*	Situation:

*	1) we use your YSF2DMR software to connect an YSY-Reflector with one connection via MMDVM to IPSC2
This work fine from/to all other connected MMDVM, HYTERA and MOTOROLA HOTSPOTS and REPEATERS
*	2) we use a MMDVM connection to the XLXD Server (as Client !) and a AMBED Server
This work fine from/to all other MMDVM, HYTERA, …
*	3) we combine this two connection via routing matrix from IPSC2
ERROR: NOW we run into the error … only the FIRST! stream (1. PTT) from C4FM via YSF-Reflector -> YSF2DMR -> IPSC2 -> XLXD
A 2nd PTT on C4FM is not heard

 

So I found that streams coming out of YSF2DMR bring always the same StreamID (Byte 16,17,18,19) in the MMDVM packet.

 

After my PATCH every PTT a new StreamID is calculated (RAND) and all is working fine.

 

Hope can help you now.

 

Btw. A very fine peace of software – Thank you

 

73 de Kurt

 

Ing. Kurt Baumann

1210 Wien

OE1KBC

 

Von: Andy CA6JAU <notifications@github.com> 
Gesendet: Dienstag, 4. September 2018 16:58
An: juribeparada/YSF2DMR <YSF2DMR@noreply.github.com>
Cc: Kurt <kbaumann@chello.at>; Author <author@noreply.github.com>
Betreff: Re: [juribeparada/YSF2DMR] No ongoing StreamID for "DMRD" YSF -> DMR (#13)

 

Maybe I didn't explain me correctly, I mean without your patch, YSF2DMR -> XLX works OK, then I don't understand your issue, can you explain what is the problem that you have?. BTW, this is a legacy YSF2DMR repository, the latest code is in MMDVM_CM.

**Comment by juribeparada** [comment]
Thank you for the explanation, then the problem is related with the StreamID is always the same. I will add your patch at night here. Thank you very much.

**Comment by juribeparada** [comment]
I added your patch

**Comment by oe1kbc** [comment]
Thank you Andy
73 from Vienna
Kurt
