### ISSUE TITLE
Jitter Buffer

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/YSF2DMR#2]
Andy, excellent work here, works like it I expected it to, any chance you can patch the DMR network to enable disabling the DMR Jitter Buffer (similar to MMDVMHost recent patches)?

**Comment by juribeparada** [comment]
Hi Andy, yes, I will do, but tell me if you have experienced any issue of JitterBuffer with this software, because in this case doesn't matter to transfer data packets between both networks, only voice packets.

**Comment by AndyTaylorTweet** [comment]
Logging this kind of thing in the YSF2DMR log:

M: 2018-02-01 19:52:54.784 YSF received end of voice transmission
D: 2018-02-01 19:53:03.259 DMR Slot 2, JitterBuffer: starting the timer
M: 2018-02-01 19:53:03.762 DMR Header received from M0GLJ to TG 31672
D: 2018-02-01 19:53:04.307 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=3, raw=12, head=12, tail=140
D: 2018-02-01 19:53:04.312 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=4, raw=12, head=12, tail=140
D: 2018-02-01 19:53:04.423 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=5, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.424 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=6, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.429 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=7, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.429 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=8, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.435 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=9, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.461 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=10, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.467 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=11, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.472 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=12, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.473 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=13, raw=14, head=14, tail=142
D: 2018-02-01 19:53:04.612 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=16, raw=17, head=17, tail=145
D: 2018-02-01 19:53:05.406 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=29, raw=30, head=30, tail=158
D: 2018-02-01 19:53:05.523 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=30, raw=32, head=32, tail=160
D: 2018-02-01 19:53:05.620 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=31, raw=33, head=33, tail=161
D: 2018-02-01 19:53:05.679 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=32, raw=34, head=34, tail=162
D: 2018-02-01 19:53:05.749 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=33, raw=36, head=36, tail=164
D: 2018-02-01 19:53:05.749 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=34, raw=36, head=36, tail=164
D: 2018-02-01 19:53:05.839 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=35, raw=37, head=37, tail=165
D: 2018-02-01 19:53:05.845 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=36, raw=37, head=37, tail=165
D: 2018-02-01 19:53:06.020 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=37, raw=40, head=40, tail=168
D: 2018-02-01 19:53:06.026 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=38, raw=40, head=40, tail=168
D: 2018-02-01 19:53:06.032 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=39, raw=40, head=40, tail=168
D: 2018-02-01 19:53:06.170 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=40, raw=43, head=43, tail=171
D: 2018-02-01 19:53:06.186 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=41, raw=43, head=43, tail=171
D: 2018-02-01 19:53:06.293 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=42, raw=45, head=45, tail=173
D: 2018-02-01 19:53:06.363 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=43, raw=46, head=46, tail=174
D: 2018-02-01 19:53:06.406 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=44, raw=47, head=47, tail=175
D: 2018-02-01 19:53:06.492 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=45, raw=48, head=48, tail=176
D: 2018-02-01 19:53:06.492 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=46, raw=48, head=48, tail=176
D: 2018-02-01 19:53:06.498 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=47, raw=48, head=48, tail=176
D: 2018-02-01 19:53:06.589 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=49, raw=50, head=50, tail=178
M: 2018-02-01 19:53:07.064 DMR received end of voice transmission
M: 2018-02-01 19:53:13.246 Received YSF Header: Src: MW0MWZ     Dst: **********
M: 2018-02-01 19:53:13.248 DMR ID of MW0MWZ: 2353150, DstID: TG 31672
M: 2018-02-01 19:53:28.645 YSF received end of voice transmission
M: 2018-02-01 19:55:05.452 Received YSF Header: Src: MW0MWZ     Dst: **********
M: 2018-02-01 19:55:05.453 DMR ID of MW0MWZ: 2353150, DstID: TG 31672
M: 2018-02-01 19:55:09.422 YSF received end of voice transmission
D: 2018-02-01 19:56:31.738 DMR Slot 2, JitterBuffer: starting the timer
M: 2018-02-01 19:56:32.245 DMR Header received from M0GLJ to TG 31672
M: 2018-02-01 19:56:33.744 DMR received end of voice transmission
D: 2018-02-01 19:56:55.371 DMR Slot 2, JitterBuffer: starting the timer
M: 2018-02-01 19:56:55.873 DMR Header received from M0GLJ to TG 31672
D: 2018-02-01 19:56:58.295 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=42, raw=43, head=43, tail=171
D: 2018-02-01 19:56:58.390 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=43, raw=44, head=44, tail=172
D: 2018-02-01 19:56:58.460 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=44, raw=46, head=46, tail=174
D: 2018-02-01 19:56:58.581 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=45, raw=48, head=48, tail=176
D: 2018-02-01 19:56:58.656 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=46, raw=49, head=49, tail=177
D: 2018-02-01 19:56:58.698 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=47, raw=50, head=50, tail=178
D: 2018-02-01 19:56:58.746 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=48, raw=50, head=50, tail=178
D: 2018-02-01 19:56:58.794 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=49, raw=51, head=51, tail=179
D: 2018-02-01 19:56:58.954 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=50, raw=54, head=54, tail=182
D: 2018-02-01 19:56:59.002 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=51, raw=55, head=55, tail=183
D: 2018-02-01 19:56:59.045 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=52, raw=55, head=55, tail=183
D: 2018-02-01 19:56:59.092 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=53, raw=56, head=56, tail=184
D: 2018-02-01 19:56:59.151 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=54, raw=57, head=57, tail=185
D: 2018-02-01 19:56:59.194 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=55, raw=58, head=58, tail=186
D: 2018-02-01 19:56:59.284 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=56, raw=59, head=59, tail=187
D: 2018-02-01 19:56:59.343 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=57, raw=60, head=60, tail=188
D: 2018-02-01 19:56:59.418 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=58, raw=62, head=62, tail=190
D: 2018-02-01 19:56:59.450 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=59, raw=62, head=62, tail=190
D: 2018-02-01 19:56:59.498 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=60, raw=63, head=63, tail=191
D: 2018-02-01 19:56:59.584 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=61, raw=64, head=64, tail=192
D: 2018-02-01 19:56:59.616 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=62, raw=65, head=65, tail=193
D: 2018-02-01 19:56:59.659 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=63, raw=66, head=66, tail=194
D: 2018-02-01 19:56:59.803 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=64, raw=68, head=68, tail=196
D: 2018-02-01 19:56:59.821 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=65, raw=68, head=68, tail=196
D: 2018-02-01 19:56:59.884 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=66, raw=69, head=69, tail=197
D: 2018-02-01 19:56:59.927 DMR Slot 2, JitterBuffer: rejecting frame with seqNo=67, raw=70, head=70, tail=198
D: 2018-02-01 19:56:59.954 Network watchdog has expired
D: 2018-02-01 19:57:00.017 DMR Slot 2, JitterBuffer: starting the timer
M: 2018-02-01 19:57:05.987 DMR received end of voice transmission
M: 2018-02-01 19:57:10.690 Received YSF Header: Src: MW0MWZ     Dst: **********
M: 2018-02-01 19:57:10.690 DMR ID of MW0MWZ: 2353150, DstID: TG 31672
M: 2018-02-01 19:57:14.660 YSF received end of voice transmission

**Comment by juribeparada** [comment]
OK, the same behaviour that in MMDVMHost when experienced network problems. I will see this during the weekend.

**Comment by AndyTaylorTweet** [comment]
Yep thats why I thought you would want to know.

**Comment by juribeparada** [comment]
Added the last G4KLX implementation for the JitterBuffer bypass, please test

**Comment by AndyTaylorTweet** [comment]
Pulling in the changes and re-compiling - I'll update with some results later.
