### ISSUE TITLE
Compile time errors

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/YSF2DMR#3]
Andy,

Below is the output for the compile - these errors were present before the latest commits and are not related to them - posting the information here so that you know about them.

All of these errors are in ModeConv.cpp, none of them stop the compile process.

----8<----
ModeConv.cpp: In member function ‘unsigned int CModeConv::getDMR(unsigned char*)’:
ModeConv.cpp:744:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (m_dmrN >= 1U) {
             ^
ModeConv.cpp:755:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (m_dmrN >= 3U) {
             ^
ModeConv.cpp: In member function ‘unsigned int CModeConv::getYSF(unsigned char*)’:
ModeConv.cpp:785:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (m_ysfN >= 1U) {
             ^
ModeConv.cpp:796:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (m_ysfN >= 5U) {
             ^
ModeConv.cpp: In member function ‘unsigned int CModeConv::getDMR(unsigned char*)’:
ModeConv.cpp:747:3: warning: ‘tag’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (tag[0U] != TAG_DATA) {
   ^
ModeConv.cpp: In member function ‘unsigned int CModeConv::getYSF(unsigned char*)’:
ModeConv.cpp:788:3: warning: ‘tag’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (tag[0U] != TAG_DATA) {
   ^
----8<----

**Comment by juribeparada** [comment]
Those are not errors, just warnings, YSF2DMR should still work.

**Comment by juribeparada** [comment]
Now warnings should be eliminated

**Comment by AndyTaylorTweet** [comment]
Confirmed - compile is now clean.
