### ISSUE TITLE
YSF Callsign-ID Lookup with extensions

### ISSUE THREAD

**Issue by ve1aic** [juribeparada/YSF2DMR#4]
Many Fusion radios have their "callsign" programmed with an extension.
eg callsign-name or callsign-info. I use a number after my callsign so I can tell which radio.
(VE1AIC-Ron or VE1AIC-7 )
So, when the DMRLookup is run it checks DMRIds.dat for a match on the full 10 chars, which will fail.
Suggest a delimiter trap to catch just the real callsign for the DMR ID Lookup.
Tks,
Ron VE1AIC

**Comment by juribeparada** [comment]
It should be fixed now, please check

**Comment by ve1aic** [comment]
Works great, thanks Andy.
My YSF TX was VE1AIC-7, converted to VE1AIC 3020008 on DMR.

73, Ron
