### ISSUE TITLE
Send NO GPS position instead of the one from your station on YSF

### ISSUE THREAD

**Issue by yo2loj** [juribeparada/YSF2DMR#5]
Hi,
The data you are sending in the YSF data is your own GPS position from your radio.
(YSF2DMR.c)
// Sample of DT1 and DT2 from my radio, GPS info + more data, I need to investigate this...
//const unsigned char dt1_temp[] = {0x34, 0x22, 0x62, 0x5F, 0x24, 0x53, 0x39, 0x54, 0x38, 0x38};
//const unsigned char dt2_temp[] = {0x52, 0x65, 0x2A, 0x3E, 0x6C, 0x22, 0x30, 0x20, 0x03, 0x8B};

The format of those fields is:
serial number (1 byte) + command (3 bytes) + radio type (1 byte) + data (13 bytes) + terminator (0x03) + checksum (1 byte)
spread into the 2 parts. The checksum is done by simple 8 bit addition of all previous bytes.

I would propose a "NO GPS" info from a FT-2D, like the Brandmeister servers:
const unsigned char dt1_temp[] = {0x34, 0x22, 0x61, 0x5F, 0x28, 0x20, 0x20, 0x20, 0x20, 0x20};
const unsigned char dt2_temp[] = {0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x03, 0xE1};

Marius, YO2LOJ

**Comment by yo2loj** [comment]
Additional info
Commands known to me (most from Jonathan):
const unsigned char DX_REQ[]    = {0x5DU, 0x71U, 0x5FU};
const unsigned char CONN_REQ[]  = {0x5DU, 0x23U, 0x5FU};
const unsigned char DISC_REQ[]  = {0x5DU, 0x2AU, 0x5FU};
const unsigned char ALL_REQ[]   = {0x5DU, 0x66U, 0x5FU};

const unsigned char DX_RESP[]   = {0x5DU, 0x51U, 0x5FU};
const unsigned char DX_RESP2[]  = {0x5DU, 0x52U, 0x5FU};
const unsigned char CONN_RESP[] = {0x5DU, 0x41U, 0x5FU};
const unsigned char DISC_RESP[] = {0x5DU, 0x41U, 0x5FU};
const unsigned char ALL_RESP[]  = {0x5DU, 0x46U, 0x5FU};

const unsigned char NULL0_GPS[] = {0x22U, 0x61U, 0x5FU};
const unsigned char SHRT_GPS[]  = {0x22U, 0x62U, 0x5FU};
const unsigned char NULL1_GPS[] = {0x47U, 0x63U, 0x5FU};
const unsigned char LONG_GPS[]  = {0x47U, 0x64U, 0x5FU};

const unsigned char GM_REQ[] = {0x47U,0x64U,0x5F}; 

And radio types I know:
0x24 - FT-1D
0x25 - FTM-400D
0x26 - DR-1X
0x27 - FT-991
0x28 - FT-2D
0x29 - FTM-100D
0x2B - FT-70D

**Comment by juribeparada** [comment]
Added to the code, thank you Marius

**Comment by yo2loj** [comment]
I assume this could be closed. Tank you.
