### ISSUE TITLE
Feature Request - DMR Monitor -Nextion 

### ISSUE THREAD

**Issue by ve1aic** [juribeparada/YSF2DMR#7]
So listening to DMR->Fusion on my FTM-100 Radio it displays the DMR Callsign and the TG properly.
eg: KD6ELK    >R  TG310

However, in the MMDVM log and the Nextion display I see only below:
(DMR Net to Fusion RF)

M: 2018-02-22 20:59:32.760 YSF, received network data from VE1AIC     to ALL        at VE1AIC    
M: 2018-02-22 21:00:40.147 YSF, network watchdog has expired, 65.9 seconds, 0% packet loss, BER: 0.0%

1. Is it possible for the network data to show "KD6ELK  to ALL at VE1AIC "?

FYI the outgoing data displays the same as the MMDVMlog here. 
2. Not as important but perhaps it should instead show the Network (DMR) data ? 

(Fusion RF ->DMR Net)
M: 2018-02-22 21:00:42.193 YSF, received RF header from VE1AIC-8   to ALL       
M: 2018-02-22 21:02:04.796 YSF, received RF end of transmission, 82.7 seconds, BER: 0.9%, RSSI: -47/-47/-47 dBm

Just asking. 
Thanks for all your work on this...waiting for a DMR TG selection interface to really make this sing.
73, Ron

I: 2018-02-22 17:03:31.239 MMDVM protocol version: 1, description: MMDVM_HS-v1.3.1 20180218 ADF7021 FW by CA6JAU GitID #48d61d2 on Zumspot-Libre

**Comment by juribeparada** [comment]
OK, the 1) should be working now, but I don't understand your 2), this is the MMDVMHost side in YSF mode, I can't mix with DMR.

**Comment by yo2loj** [comment]
Checked 1) and it fits. Tnx.

**Comment by ve1aic** [comment]
Yes, thanks Andy and others for comments. Was just putting thoughts out there, the Nextion display stays in Fusion mode for both incoming (DMR->Fusion) and outgoing (Fusion->DMR).
Now it displays in MMDVM log and Nextion the incoming data as requested with the DMR Callsign.
73, Ron VE1AIC

M: 2018-02-23 02:06:52.507 YSF, received network data from KD6ELK     to ALL        at VE1AIC    
M: 2018-02-23 02:07:23.082 YSF, network watchdog has expired, 29.1 seconds, 0% packet loss, BER: 0.0%
M: 2018-02-23 02:07:30.139 YSF, received network data from K0EHT      to ALL        at VE1AIC    
M: 2018-02-23 02:07:52.739 YSF, received network end of transmission, 22.6 seconds, 0% packet loss, BER: 0.0%
