### ISSUE TITLE
Feature request: Drop FR_DATA and FR_VOICE forward to DMR

### ISSUE THREAD

**Issue by yo2loj** [juribeparada/YSF2DMR#8]
Since forwarded data packets make no sense to DMR, and FR_VOICE is not transcodable, wouldn't it make sense to drop those after decoding the FICH and identifying them as such?
Use case 1: if someone would turn on GM on the YSF side, there would be a position report every 20 sec which would trigger a DMR transmition each time.
Use case 2: 2 people talking via VW mode on the YSF reflector would cause DMR activity which is virtually just silence to the DMR listeners (we where running a BM gateway and had actual complains of this "private mode" of some C4FM users).

**Comment by juribeparada** [comment]
You are right, that is bug, now it should be fixed.

**Comment by yo2loj** [comment]
Man, you are fast :-)
Everything working as expected.
